version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile 
    image: react_frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
